# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import QFileDialog

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setWindowOpacity(0.5)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(652, 394)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 0, 651, 341))
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 652, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.ExitMenuItem = QtWidgets.QAction(MainWindow)
        self.ExitMenuItem.setObjectName("ExitMenuItem")
        self.Save_AsMenuItem = QtWidgets.QAction(MainWindow)
        self.Save_AsMenuItem.setObjectName("Save_AsMenuItem")
        self.NewMenuItem = QtWidgets.QAction(MainWindow)
        self.NewMenuItem.setObjectName("NewMenuItem")
        self.menuFile.addAction(self.NewMenuItem)
        self.menuFile.addAction(self.Save_AsMenuItem)
        self.menuFile.addAction(self.ExitMenuItem)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Text Editor"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.ExitMenuItem.setText(_translate("MainWindow", "Exit"))
        self.Save_AsMenuItem.setText(_translate("MainWindow", "Save As..."))
        self.NewMenuItem.setText(_translate("MainWindow", "New"))

class MyApp(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.connect_triggers()
        self.show()  # Ensure the main window is shown

    def connect_triggers(self):
        self.ui.ExitMenuItem.triggered.connect(self.exit_application)
        self.ui.Save_AsMenuItem.triggered.connect(self.save_as)
        self.ui.NewMenuItem.triggered.connect(self.new_file)

    def exit_application(self):
        # Define what happens when ExitMenuItem is triggered
        sys.exit()

    def save_as(self):
        options = QFileDialog.Options()
        file_name, _ = QFileDialog.getSaveFileName(self, "Save As", "", "Text Files (*.txt);;All Files (*)", options=options)

        if file_name:
            # Get the text from plainTextEdit
            text = self.ui.plainTextEdit.toPlainText()
            # Write the text to the chosen file
            with open(file_name, 'w') as file:
                file.write(text)

    def new_file(self):
        self.ui.plainTextEdit.clear()

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = MyApp()
    sys.exit(app.exec_())  # Ensure the application runs until closed
